#!/bin/bash
set -e
set -o pipefail

BUILDPACK_ROOT=$(cd $(dirname "$0")/..; pwd)
for filename in $(find ${BUILDPACK_ROOT}/lib/*.bash); do source $filename; done

DEPLOY_ROOT=$(heroku-dir)
NGINX_ROOT=$(heroku-vendor-dir nginx)
NGINX_PREFIX="nginx-${NGINX_VERSION}"

temp-dir-start

echo "Preparing" | heroku-notice
echo "Downloading nginx v${NGINX_VERSION} source" | heroku-indent
url-download "http://nginx.org/download/${NGINX_PREFIX}.tar.gz" $(pwd)

echo "Downloading pcre v${PCRE_VERSION} source" | heroku-indent
url-download "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-${PCRE_VERSION}.tar.gz" ${NGINX_PREFIX}/contrib

echo "Compiling" | heroku-notice
vulcan build -v -s $NGINX_PREFIX -o ${NGINX_PREFIX}.tar.gz -p $NGINX_ROOT -c \
    "CFLAGS=-s ./configure \
        --prefix=${NGINX_ROOT} \
        --with-pcre=contrib/pcre-${PCRE_VERSION} \
        --http-fastcgi-temp-path=/tmp/fastcgi \
        --http-client-body-temp-path=/tmp/client_body \
        --with-http_ssl_module \
        --with-http_gzip_static_module \
        --with-http_stub_status_module \
        --with-http_realip_module \
        --without-http_ssi_module \
        --without-http_userid_module \
        --without-http_access_module \
        --without-http_autoindex_module \
        --without-http_geo_module \
        --without-http_map_module \
        --without-http_split_clients_module \
        --without-http_proxy_module \
        --without-http_uwsgi_module \
        --without-http_scgi_module \
        --without-http_memcached_module \
        --without-http_limit_conn_module \
        --without-http_limit_req_module \
        --without-http_empty_gif_module \
        --without-http_browser_module \
        --without-http_upstream_ip_hash_module \
        --without-http_upstream_least_conn_module \
        --without-http_upstream_keepalive_module \
    && make install" | heroku-indent

echo "Uploading ${NGINX_PREFIX}.tar.gz to Amazon S3" | heroku-notice
s3-upload "${NGINX_PREFIX}.tar.gz" "${NGINX_PREFIX}.tar.gz" $1

temp-dir-end
