#!/bin/bash
set -e
source $(dirname $0)/common

PHP_URL="http://au1.php.net/distributions/php-${PHP_VERSION}.tar.bz2"
PHP_PREFIX="php-${PHP_VERSION}"

tempdir=$(make-temp-dir)
cd $tempdir

echo "Working directory: ${tempdir}"
echo

echo "Downloading php v${PHP_VERSION} ..."
curl ${PHP_URL} -o php.tar.bz2
echo
tar xzf php.tar.bz2

# build for heroku
echo "Building ..."
vulcan build -v -s $PHP_PREFIX -o $tempdir/$PHP_PREFIX.tar.gz -p /app/vendor/php -c \
    "./configure  --prefix=/app/vendor/php \
                  --with-pgsql \
                  --with-pdo-pgsql \
                  --with-iconv \
                  --with-gd \
                  --with-curl=/usr/lib \
                  --with-config-file-path=/app/vendor/php \
                  --with-openssl \
                  --enable-fpm \
                  --with-zlib \
                  --enable-mbstring \
                  --disable-debug \
                  --disable-rpath \
                  --enable-gd-native-ttf \
                  --enable-inline-optimization \
                  --with-bz2 \
                  --enable-pcntl \
                  --enable-mbregex \
                  --with-mhash \
                  --enable-zip \
                  --with-pcre-regex \
                  --enable-libxml \
                  --with-gettext \
                  --with-jpeg-dir \
                  --with-mysqli \
                  --with-pcre-regex \
                  --with-png-dir \
                  --without-pdo-sqlite \
                  --without-sqlite3 \
                  && make install \
                  && /app/vendor/php/bin/pear config-set php_dir /app/vendor/php \
                  && yes '' | /app/vendor/php/bin/pecl install memcache \
                  && yes '' | /app/vendor/php/bin/pecl install apc-3.1.13"

echo "Uploading to S3 ..."
s3-upload "${tempdir}/${PHP_PREFIX}.tar.gz" "${PHP_PREFIX}.tar.gz" $1

echo "Cleaning up ..."
rm -rf $tempdir
