#!/bin/bash
set -e
source $(dirname $0)/common

NGINX_URL="http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz"
NGINX_PREFIX="nginx-${NGINX_VERSION}"

PCRE_VERSION=8.32
PCRE_URL="ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-${PCRE_VERSION}.tar.gz"

tempdir=$(make-temp-dir)
cd $tempdir

echo "Working directory: ${tempdir}"
echo

# Download and unpack nginx ...
echo "Downloading nginx v${NGINX_VERSION} ..."
curl ${NGINX_URL} -o nginx.tar.gz
echo
tar xzf nginx.tar.gz

# Download and unpack 
pushd ${NGINX_PREFIX}/contrib
echo "Downloading pcre v${PCRE_VERSION} ..."
curl $PCRE_URL -o pcre.tar.gz
echo
tar zxf pcre.tar.gz
popd

# build for heroku
echo "Building ..."
vulcan build -v -s $NGINX_PREFIX -o $tempdir/$NGINX_PREFIX.tar.gz -p /app/vendor/nginx -c \
  "./configure --prefix=/app/vendor/nginx \
               --with-pcre=contrib/pcre-${PCRE_VERSION} \
               --with-http_ssl_module \
               --with-http_gzip_static_module \
               --with-http_stub_status_module \
               --with-http_realip_module \
               && make install"

echo "Uploading to S3 ..."
s3-upload "${tempdir}/${NGINX_PREFIX}.tar.gz" "${NGINX_PREFIX}.tar.gz" $1

echo "Cleaning up ..."
rm -rf $tempdir
