#!/bin/bash
set -e
source $(dirname $0)/common

PHP_URL="http://au1.php.net/distributions/php-${PHP_VERSION}.tar.bz2"
PHP_PREFIX="php-${PHP_VERSION}"

tempdir=$(make-temp-dir)
cd $tempdir

echo "Working directory: ${tempdir}"
echo

echo "Downloading php v${PHP_VERSION} ..."
curl ${PHP_URL} -o php.tar.bz2
echo
tar xzf php.tar.bz2

# build for heroku
echo "Building ..."
vulcan build -v -s $PHP_PREFIX -o $tempdir/$PHP_PREFIX.tar.gz -p $ROOT/vendor/php -c \
    "CFLAGS=-s ./configure \
        --prefix=${ROOT}/vendor/php \
        --with-config-file-path=${ROOT}/vendor/php \
        --enable-fpm \
        --with-pgsql \
        --with-pdo-pgsql \
        --with-iconv \
        --with-curl=/usr/lib \
        --with-openssl \
        --with-zlib \
        --with-bz2 \
        --with-pcre-regex \
        --with-gettext \
        --with-pcre-regex \
        --without-cdb \
        --disable-flatfile \
        --disable-inifile \
        --without-sqlite3 \
        --without-pdo-sqlite \
        --enable-zip \
        --enable-mbstring \
        --enable-mbregex \
        --enable-inline-optimization \
        --enable-libxml \
        --disable-debug \
        --disable-rpath \
        --disable-cgi \
        && make install \
        && ${ROOT}/vendor/php/bin/pear config-set php_dir ${ROOT}/php \
        && yes '' | ${ROOT}/vendor/php/bin/pecl install memcache \
        && yes '' | ${ROOT}/vendor/php/bin/pecl install apc-3.1.13"

        # --with-gd \
        # --enable-gd-native-ttf \
        # --with-jpeg-dir \
        # --with-png-dir \

echo "Uploading to S3 ..."
s3-upload "${tempdir}/${PHP_PREFIX}.tar.gz" "${PHP_PREFIX}.tar.gz" $1

echo "Cleaning up ..."
rm -rf $tempdir
